# Generated by Django 3.2.5 on 2025-05-07 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pdfocus_app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdfocus_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='page_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='file',
            field=models.FileField(upload_to=pdfocus_app.models.user_pdf_path),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
