# Generated by Django 5.2 on 2025-06-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfocus_app', '0002_auto_20250507_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='doc_type',
            field=models.CharField(choices=[('book', 'Книга'), ('article', 'Статья'), ('report', 'Отчет'), ('other', 'Другое')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
