# Generated by Django 5.2 on 2025-06-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfocus_app', '0003_alter_pdfdocument_doc_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='theme',
            field=models.TextField(blank=True, null=True),
        ),
    ]
