# Generated by Django 5.2 on 2025-06-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfocus_app', '0004_alter_pdfdocument_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
